"""add image_url to task_block

Revision ID: 019744937dd1
Revises: 299a49ba0e08
Create Date: 2026-01-03 03:15:17.276459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '019744937dd1'
down_revision = '299a49ba0e08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_blocks', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
