"""add team name field

Revision ID: 299a49ba0e08
Revises: 4e4cf0ee3061
Create Date: 2026-01-03 03:10:29.187788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299a49ba0e08'
down_revision = '4e4cf0ee3061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала добавляем поле как nullable, чтобы можно было заполнить существующие записи
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=200), nullable=True))
    
    # Заполняем существующие записи: используем member1 как название команды
    op.execute("UPDATE teams SET name = member1 WHERE name IS NULL")
    
    # Теперь делаем поле обязательным
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.alter_column('name', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
