"""Examples

Revision ID: 333f0b3e7386
Revises: b3fe7c3eca60
Create Date: 2025-12-28 16:27:08.032968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '333f0b3e7386'
down_revision = 'b3fe7c3eca60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('correct_answer', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('type')

    op.drop_table('task_examples')
    # ### end Alembic commands ###
