"""Add TournamentState

Revision ID: 501035e3c896
Revises: 1879b8504366
Create Date: 2025-12-27 15:29:02.173404

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '501035e3c896'
down_revision = '1879b8504366'
branch_labels = None
depends_on = None


def upgrade():
    from sqlalchemy.dialects import postgresql
    tournament_state_enum = postgresql.ENUM(
        "waiting",
        "running",
        "finished",
        name="tournament_state"
    )

    tournament_state_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', postgresql.ENUM('WAITING', 'RUNNING', 'FINISHED', name='tournament_state'), nullable=False))
        batch_op.add_column(sa.Column('start_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_column('start_time')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('start_at')
        batch_op.drop_column('state')
    from sqlalchemy.dialects import postgresql

    tournament_state_enum = postgresql.ENUM(
        "waiting",
        "running",
        "finished",
        name="tournament_state"
    )

    tournament_state_enum.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
