"""Answers

Revision ID: 6abf6db7ce8e
Revises: 333f0b3e7386
Create Date: 2025-12-28 18:46:59.608265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6abf6db7ce8e'
down_revision = '333f0b3e7386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('example_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('answers_team_id_task_id_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['team_id', 'task_id', 'example_id'])
        batch_op.create_foreign_key(None, 'task_examples', ['example_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('answers_team_id_task_id_key'), ['team_id', 'task_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('points')
        batch_op.drop_column('example_id')

    # ### end Alembic commands ###
