"""Answers & Task Example

Revision ID: 928ed1a729ee
Revises: 6abf6db7ce8e
Create Date: 2025-12-28 19:10:29.374180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928ed1a729ee'
down_revision = '6abf6db7ce8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_examples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True))
        batch_op.alter_column('task_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_examples', schema=None) as batch_op:
        batch_op.alter_column('task_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('points')

    # ### end Alembic commands ###
