"""TeamBlockStart

Revision ID: 997fb2248799
Revises: 99862b3cb289
Create Date: 2026-01-06 22:20:46.648753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997fb2248799'
down_revision = '99862b3cb289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_block_start',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['task_blocks.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_block_start')
    # ### end Alembic commands ###
