"""Add password hash to teams & other

Revision ID: 99862b3cb289
Revises: 019744937dd1
Create Date: 2026-01-06 19:42:55.844673

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99862b3cb289'
down_revision = '019744937dd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('max_duration', sa.Integer(), nullable=False))
        batch_op.drop_column('duration')
        batch_op.drop_column('start_offset')

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_column('state')
        batch_op.drop_column('start_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('state', postgresql.ENUM('waiting', 'running', 'finished', name='tournament_state'), autoincrement=False, nullable=False))

    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('started_at')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('task_blocks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_offset', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('max_duration')
        batch_op.drop_column('order')

    # ### end Alembic commands ###
